def display_board(board = [" ", " ", " ", " ", " ", " ", " ", " ", " "])
  puts "   |   |   "
  puts "-----------"
  puts "   |   |   "
  puts "-----------"
  puts "   |   |   "
  board[0] = "O, O, X, X, X, O"
  board[1] = "X, X, O"
  board[2] = "X, O, X, O"
  board[3] = "X, O"
  board[4] = "X, X, X, O, X, O"
  board[5] = "X,O"
  board[6] = "O, O, X, O"
  board[7] = "O, X, O  "
  board[8] = "O, X, X, O"
end
