def display_board(board = [" ", " ", " ", " ", " ", " ", " ", " ", " "])
  puts "   |   |   "
  puts "-----------"
  puts "   |   |   "
  puts "-----------"
  puts "   |   |   "
  puts board[0] = "O, O, X, X, X, O"
  puts board[1] = "X, X, O"
  puts board[2] = "X, O, X, O"
  puts board[3] = "X, O"
  puts board[4] = "X, X, X, O, X, O"
  puts board[5] = "X,O"
  puts board[6] = "O, O, X, O"
  puts board[7] = "O, X, O  "
  puts board[8] = "O, X, X, O"
end
